### ISSUE TITLE
嵌套fragment的问题

### ISSUE THREAD

**Issue by pengbs** [xmagicj/LazyFragment#2]
如果viewpager+fragment里面再嵌套viewpager+fragment，最里面的fragment不会延迟加载

**Comment by xmagicj** [comment]
是initData没执行 还是initData每次都执行?

**Comment by pengbs** [comment]
子fragment还没有显示出来的时候就执行了，没有起到懒加载的作用，不过这个只在viewpager+fragment嵌套viewpager+fragment会出现

**Comment by xmagicj** [comment]
好的我这边试试

**Comment by xmagicj** [comment]
找到原因了 Fragment被PagerAdapter初始化后会调用
setPrimaryItem()方法
其中会设置
fragment.setUserVisibleHint(true);
也就是说 如果你是ViewPager嵌套ViewPager 
第二个主节点的Fragment就会调用setPrimaryItem()方法
然后主节点下的子Fragment就会执行fragment.setUserVisibleHint(true);
导致initData执行

也就是说你的主节点Fragment没有用lazy的模式
可以尝试把
mViewPager.setAdapter(mSectionsPagerAdapter); 
放到主节点Fragment里的initData()里面执行 就好了
亲测有效

**Comment by pengbs** [comment]
万分感谢，我试试看
