### ISSUE TITLE
如果fragment的个数不定

### ISSUE THREAD

**Issue by ohyes666** [xmagicj/LazyFragment#4]
如果fragment的个数不确定的场景，viewpager如何直接刷新所有fragment呢。

**Comment by xmagicj** [comment]
没有特别明白 不确定是指???
因为本身Fragment个数 在例子里面是支持配置的(new出来的嘛)
而且ViewPager+Adapter的组合也必须要有一个数量的Fragment才能初始化呀.

所以道理是 new了多少个 Fragment 就会刷新多少个.

或者你再描述清楚一下你的场景.
